// Built-in sample datasets.
//
// IMPORTANT: this is fictional data that mirrors the *shape* of the real
// sheet (med-spa cold-outreach CRM + Expenses tab). Real business data never
// lives in the repo — it is served only at runtime through the private
// backend proxy.
//
// Each record matches the normalized shapes produced by the proxy
// (see api/_sheet.js and api/_expenses.js) and consumed by
// src/lib/aggregate.js.

export const sampleContacts = [
  {
    firstName: 'Gina', lastName: 'Avery', email: 'gina@example-medspa.com',
    company: 'Coastline Aesthetics', title: 'Owner / Nurse Practitioner',
    industry: 'Med Spa / Aesthetics', employeeCount: 8,
    location: 'San Diego (Carmel Valley), CA', linkedinUrl: '',
    source: 'ICP Research – SD Med Spa', outreachStatus: 'New Client',
    dateSent: '', emailSubject: '', notes: 'Single-location, owner-operated. Closed weekends.',
    phone: '(858) 555-0108', emailConfidence: 'High', contactScore: 91,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Marcus', lastName: 'Bell', email: 'marcus@example-medspa.com',
    company: 'La Mesa Skin & Laser', title: 'Owner / Medical Director (MD)',
    industry: 'Med Spa / Aesthetics', employeeCount: 14,
    location: 'La Mesa, CA', linkedinUrl: '',
    source: 'ICP Research – SD Med Spa', outreachStatus: 'Contacted',
    dateSent: '2026-05-21', emailSubject: 'Quick question about after-hours bookings',
    notes: 'Running first-visit promos, limited hours.',
    phone: '(619) 555-0119', emailConfidence: 'High', contactScore: 88,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Priya', lastName: 'Chandra', email: 'priya@example-medspa.com',
    company: 'Hillcrest Aesthetica', title: 'Owner / Medical Director (MD)',
    industry: 'Med Spa / Aesthetics', employeeCount: 11,
    location: 'San Diego (Hillcrest), CA', linkedinUrl: '',
    source: 'LinkedIn Outreach', outreachStatus: 'Replied',
    dateSent: '2026-05-18', emailSubject: 'After-hours missed-call capture',
    notes: 'Booking via Vagaro. Interested, asked for pricing.',
    phone: '(619) 555-0143', emailConfidence: 'Medium', contactScore: 76,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Daniel', lastName: 'Ortiz', email: 'daniel@example-medspa.com',
    company: 'South Bay Boutique Med Spa', title: 'Co-Owner',
    industry: 'Med Spa / Aesthetics', employeeCount: 6,
    location: 'Chula Vista, CA', linkedinUrl: '',
    source: 'LinkedIn Outreach', outreachStatus: 'Booked',
    dateSent: '2026-05-12', emailSubject: 'Demo follow-up',
    notes: 'Clinical owners, ops likely manual. Demo booked for next week.',
    phone: '(619) 555-0188', emailConfidence: 'High', contactScore: 94,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Renee', lastName: 'Park', email: 'renee@example-medspa.com',
    company: 'BroTox City Heights', title: 'Owner / Nurse Injector',
    industry: 'Med Spa / Aesthetics', employeeCount: 4,
    location: 'San Diego (City Heights), CA', linkedinUrl: '',
    source: 'ICP Research – SD Med Spa', outreachStatus: 'Contacted',
    dateSent: '2026-05-22', emailSubject: 'Your IG DMs are piling up',
    notes: 'Solo-injector model, growing brand. Confirm owner name.',
    phone: '(858) 555-0162', emailConfidence: 'Low', contactScore: 64,
    humanReviewNeeded: 'Yes',
  },
  {
    firstName: 'Tom', lastName: 'Whitfield', email: 'tom@example-medspa.com',
    company: 'Del Mar Rejuvenation', title: 'Practice Manager',
    industry: 'Med Spa / Aesthetics', employeeCount: 22,
    location: 'Del Mar, CA', linkedinUrl: '',
    source: 'Referral', outreachStatus: 'New Client',
    dateSent: '', emailSubject: '', notes: 'Referred by existing contact.',
    phone: '(858) 555-0177', emailConfidence: 'High', contactScore: 82,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Alyssa', lastName: 'Reed', email: 'alyssa@example-medspa.com',
    company: 'Pacific Beach Glow Bar', title: 'Owner',
    industry: 'Med Spa / Aesthetics', employeeCount: 5,
    location: 'San Diego (Pacific Beach), CA', linkedinUrl: '',
    source: 'Cold Email', outreachStatus: 'Not Interested',
    dateSent: '2026-05-09', emailSubject: 'Missed bookings after hours?',
    notes: 'Replied not interested — already has a solution.',
    phone: '(858) 555-0193', emailConfidence: 'Medium', contactScore: 41,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Victor', lastName: 'Nguyen', email: 'victor@example-medspa.com',
    company: 'Eastlake Aesthetics', title: 'Owner / Medical Director (MD)',
    industry: 'Med Spa / Aesthetics', employeeCount: 9,
    location: 'Chula Vista (Eastlake), CA', linkedinUrl: '',
    source: 'ICP Research – SD Med Spa', outreachStatus: 'Contacted',
    dateSent: '2026-05-25', emailSubject: 'Weekend Botox inquiries',
    notes: 'Closed Sun. Weekend inquiries hit voicemail.',
    phone: '(619) 555-0204', emailConfidence: 'High', contactScore: 79,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Sofia', lastName: 'Marin', email: 'sofia@example-medspa.com',
    company: 'North County Skin Studio', title: 'Owner',
    industry: 'Med Spa / Aesthetics', employeeCount: 7,
    location: 'Escondido, CA', linkedinUrl: '',
    source: 'Cold Email', outreachStatus: 'Bounced',
    dateSent: '2026-05-14', emailSubject: 'Quick question',
    notes: 'Email bounced — needs a verified address.',
    phone: '', emailConfidence: 'Low', contactScore: 0,
    humanReviewNeeded: 'Yes',
  },
  {
    firstName: 'Henry', lastName: 'Cole', email: 'henry@example-medspa.com',
    company: 'Gaslamp Med Aesthetics', title: 'Owner / Medical Director (MD)',
    industry: 'Med Spa / Aesthetics', employeeCount: 18,
    location: 'San Diego (Downtown), CA', linkedinUrl: '',
    source: 'Referral', outreachStatus: 'Replied',
    dateSent: '2026-05-19', emailSubject: 'Front-desk follow-up gaps',
    notes: 'Asked for a one-pager. Warm.',
    phone: '(619) 555-0216', emailConfidence: 'High', contactScore: 86,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Kayla', lastName: 'Stone', email: 'kayla@example-medspa.com',
    company: 'Encinitas Wellness & Aesthetics', title: 'Owner / Nurse Practitioner',
    industry: 'Med Spa / Aesthetics', employeeCount: 10,
    location: 'Encinitas, CA', linkedinUrl: '',
    source: 'LinkedIn Outreach', outreachStatus: 'New Client',
    dateSent: '', emailSubject: '', notes: 'Strong reviews, active ad spend.',
    phone: '(760) 555-0231', emailConfidence: 'Medium', contactScore: 73,
    humanReviewNeeded: 'No',
  },
  {
    firstName: 'Brandon', lastName: 'Lee', email: 'brandon@example-medspa.com',
    company: 'Mission Valley Laser Lounge', title: 'Co-Owner',
    industry: 'Med Spa / Aesthetics', employeeCount: 13,
    location: 'San Diego (Mission Valley), CA', linkedinUrl: '',
    source: 'ICP Research – SD Med Spa', outreachStatus: 'Booked',
    dateSent: '2026-05-16', emailSubject: 'Demo confirmed',
    notes: 'Demo confirmed. High intent.',
    phone: '(619) 555-0247', emailConfidence: 'High', contactScore: 96,
    humanReviewNeeded: 'No',
  },
]

// Fictional business spend matching the Expenses tab shape
// (date, category, vendor, description, amount).
export const sampleExpenses = [
  { date: '2026-02-03', category: 'Software', vendor: 'Google Workspace', description: 'Email + Drive (2 seats)', amount: 28 },
  { date: '2026-02-05', category: 'Software', vendor: 'Apollo.io', description: 'Lead database subscription', amount: 99 },
  { date: '2026-02-11', category: 'Marketing', vendor: 'Canva', description: 'Pro plan — outreach creatives', amount: 15 },
  { date: '2026-02-18', category: 'Contractors', vendor: 'Upwork', description: 'List-building VA (10 hrs)', amount: 180 },
  { date: '2026-03-02', category: 'Software', vendor: 'Google Workspace', description: 'Email + Drive (2 seats)', amount: 28 },
  { date: '2026-03-04', category: 'Software', vendor: 'Apollo.io', description: 'Lead database subscription', amount: 99 },
  { date: '2026-03-09', category: 'Software', vendor: 'Make.com', description: 'Automation scenarios', amount: 34 },
  { date: '2026-03-15', category: 'Marketing', vendor: 'Namecheap', description: 'Outreach domains (3)', amount: 42 },
  { date: '2026-03-21', category: 'Contractors', vendor: 'Upwork', description: 'List-building VA (14 hrs)', amount: 252 },
  { date: '2026-04-01', category: 'Software', vendor: 'Google Workspace', description: 'Email + Drive (2 seats)', amount: 28 },
  { date: '2026-04-03', category: 'Software', vendor: 'Apollo.io', description: 'Lead database subscription', amount: 99 },
  { date: '2026-04-08', category: 'Software', vendor: 'Make.com', description: 'Automation scenarios', amount: 34 },
  { date: '2026-04-12', category: 'Marketing', vendor: 'Instantly.ai', description: 'Email warm-up + sending', amount: 97 },
  { date: '2026-04-19', category: 'Travel', vendor: 'Uber', description: 'Client demo — downtown SD', amount: 46 },
  { date: '2026-04-26', category: 'Contractors', vendor: 'Upwork', description: 'Copywriter — email sequences', amount: 320 },
  { date: '2026-05-01', category: 'Software', vendor: 'Google Workspace', description: 'Email + Drive (2 seats)', amount: 28 },
  { date: '2026-05-04', category: 'Software', vendor: 'Apollo.io', description: 'Lead database subscription', amount: 99 },
  { date: '2026-05-07', category: 'Software', vendor: 'Make.com', description: 'Automation scenarios', amount: 34 },
  { date: '2026-05-11', category: 'Marketing', vendor: 'Instantly.ai', description: 'Email warm-up + sending', amount: 97 },
  { date: '2026-05-16', category: 'Meals', vendor: 'Blue Bottle Coffee', description: 'Prospect coffee meeting', amount: 21 },
  { date: '2026-05-22', category: 'Marketing', vendor: 'Namecheap', description: 'Outreach domain renewals', amount: 28 },
  { date: '2026-05-28', category: 'Contractors', vendor: 'Upwork', description: 'List-building VA (8 hrs)', amount: 144 },
]
